service: exclude-development-dependencies

custom: ${file(./env.js)}

provider:
  name: google
  region: ${self:custom.region}
  runtime: nodejs
  project: ${self:custom.projectId}
  credentials: ${self:custom.credentials}

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    # - node_modules/**
    # - .gitignore
    # - .git/**
    - ./**
  include:
    - ./src/**/*.js
    - package.json
    - package-lock.json
    - index.js

functions:
  - ${file(./src/modules/book/functions.yml)}
