service: quick-start # NOTE: Don't put the word "google" in here

provider:
  name: google
  runtime: nodejs8
  region: us-central1
  project: shadowsocks-218808
  # the path to the credentials file needs to be absolute
  credentials: /Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/.gcp/shadowsocks-218808-18201f441a6b.json
  labels:

plugins:
  # - serverless-google-cloudfunctions
  - serverless-cloudfunction-offline

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: path
    labels:
  event:
    handler: event
    events:
      - event:
          eventType: google.pubsub.topic.publish
          resource: projects/shadowsocks-218808/topics/slideshowp2
    labels:
  GCS:
    handler: GCS
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: projects/shadowsocks-218808/buckets/slideshowp2
    labels:
