frameworkVersion: '=1.32.0'

service: nodejs-serverless-framework

custom: ${file(./env.js)}

provider:
  name: google
  runtime: ${self:custom.RUNTIME}
  project: ${env:PROJECT_ID}
  region: ${self:custom.REGION}
  credentials: ${env:CREDENTIALS}
  environment:
    PROJECT_ID: ${env:PROJECT_ID}

plugins:
  - serverless-google-cloudfunctions
  - serverless-dotenv-plugin

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  - ${file(./src/modules/book/functions.yml)}
  - ${file(./src/modules/gcp-get-started/functions.yml)}
  - ${file(./src/modules/gcp-background-function/functions.yml)}
  - ${file(./src/modules/gcp-storage-trigger/functions.yml)}
