frameworkVersion: '=1.32.0'

service: flexable-deploy

provider:
  name: google
  runtime: nodejs
  project: just-aloe-212502
  credentials: /Users/ldu020/workspace/nodejs-serverless-framework/.gcp/nodejs-starter-7e52b0f6fe39.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  - ${file(./src/modules/post/serverless.yml):functions}
  - ${file(./src/modules/user/serverless.yml):functions}
