frameworkVersion: '=1.32.0'

service: flexable-deploy

provider:
  name: google
  runtime: nodejs
  project: shadowsocks-218808
  credentials: /Users/ldu020/workspace/nodejs-serverless-framework/.gcp/shadowsocks-218808-08093a4cffe3.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - ./**

  include:
    - src/**/*.js
    - env.js
    - index.js
    - package.json
    - package-lock.json

functions:
  createPost:
    handler: createPost
    events:
      - http: path
  updatePost:
    handler: updatePost
    events:
      - http: path
